version: 0.2
phases:
  install:
    commands:
      - echo "[INSTALL] nothing to install"
  pre_build:
    commands:
      - echo "[PRE_BUILD] start"
  build:
    commands:
      - echo "[BUILD] nothing to build"
  post_build:
    commands:
      - echo "[POST_BUILD] deploying index.html to S3://auto-deployment-01/"
      - aws s3 cp index.html s3://auto-deployment-01/  # Entferne --acl public-read
