version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Nothing to install"
  build:
    commands:
      - echo "Build phase - nothing to build"
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 cp index.html s3:auto-deployment-01/ --acl public-read

artifacts:
  files:
    - index.html
